" disable windows sound
set visualbell
" add line numbers and relative line numbers
set nu
set rnu

" file explorer settings
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 20


" Plugins using vim-plug
call plug#begin('~/.vim/plugged')

	Plug 'flazz/vim-colorschemes'
	Plug 'hashivim/vim-terraform'
	Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()


" enable colorscheme for *tf files
autocmd BufEnter *.tf* colorscheme icansee

" enable folding in terraform files
"let g:terraform_fold_sections=1

" use different colorscheme for vimdiffs
if &diff
	    colorscheme Monokai
endif

" Custom remappings
:nmap <space>e :Vexplore<CR>
:nmap QQ :qa<CR>
